var Promise=TrelloPowerUp.Promise,randomBadgeColor=function(){return["green","yellow","red","none"][Math.floor(4*Math.random())]},convertMinsToHrsMins=function(b){var c=Math.floor(b/60);b%=60;return(10>c?"0"+c:c)+":"+(10>b?"0"+b:b)},getBackgroundBages=function(b,c){return b.card("name").get("name").then(function(a){return[{dynamic:function(){return b.get("card","shared","startTime","null").then(function(a){if("null"===a||0==a.startTime)return{color:"none",timer:"00:00",title:"Timer"};if(a.recordTime){var b=
a.previousTime;a=Math.floor((new Date-new Date(a.startTime))/1E3/60)+b;return{color:"green",timer:convertMinsToHrsMins(a),title:"Recording Time"}}b=a.previousTime;a=Math.floor((new Date(a.stopTime)-new Date(a.startTime))/1E3/60)+b;return{color:"yellow",timer:convertMinsToHrsMins(a),title:"Timer Stopped"}}).then(function(a){return{title:a.title,text:a.timer,color:a.color,refresh:61}})}},{dynamic:function(){return b.get("card","shared","assignedTo","null").then(function(a){return"null"===a||a.includes("None")?
{title:"Assign To",text:"?",color:"yellow",refresh:10}:{title:"Assigned To",text:a,color:"green",refresh:10}})}},{dynamic:function(){return b.get("card","shared","startDate","null").then(function(a){return"null"===a||2>a.length?{title:"Start Date",text:"?",color:"yellow",refresh:10}:{title:"Start Date",text:a,color:"green",refresh:10}})}}]})},getBadges=function(b){return b.card("name").get("name").then(function(c){return[{dynamic:function(){return b.get("card","shared","startTime","null").then(function(a){if("null"===
a||0==a.startTime)return{color:"none",timer:"0",title:"Timer"};if(a.recordTime){var b=a.previousTime;a=Math.floor((new Date-new Date(a.startTime))/1E3/60)+b;return{color:"green",timer:convertMinsToHrsMins(a),title:"Recording Time"}}b=a.previousTime;a=Math.floor((new Date(a.stopTime)-new Date(a.startTime))/1E3/60)+b;return{color:"none",timer:convertMinsToHrsMins(a),title:"Timer Stopped"}}).then(function(a){return{title:a.title,text:a.timer,color:a.color,refresh:61}})}},{dynamic:function(){return b.get("card",
"shared","estimatedTime","null").then(function(a){return a}).then(function(a){return"null"===a||1>a.length?{title:"Estimated Time",text:"Estimate missing",color:"red",refresh:10}:{title:"Estimated Time",text:a,color:"green",refresh:10}})}},{dynamic:function(){return b.get("card","shared","assignedTo","null").then(function(a){return a}).then(function(a){return"null"===a||a.includes("None")?{title:"Assigned To",text:"Not Assigned",color:"none",refresh:10}:{title:"Assigned To",text:a,color:"green",refresh:10}})}},
{dynamic:function(){return b.get("card","shared","startDate","null").then(function(a){return"null"===a||1>a.length?{title:"Start Date",text:"Not Planned",color:"none",refresh:10}:{title:"Start Date",text:a,color:"green",refresh:10}})}}]})},boardButtonCallback=function(b){return b.popup({title:"Reports",items:[{text:"Today",callback:function(b){b.getAll().then(function(a){b.board("members").then(function(c){return b.overlay({url:"./time-reports.html",args:{boardData:a.board.shared,recording:a.board["private"].recording}}).then(function(){return b.closePopup()})})})}},
{text:"Total time logged on this project",callback:function(b){return b.overlay({url:"./overlay.html",args:{rand:(100*Math.random()).toFixed(0)}}).then(function(){return b.closePopup()})}}]})};
TrelloPowerUp.initialize({"board-buttons":function(b,c){return b.get("board","private","recording").then(function(a){return a&&a.status?[{text:"Timer is ON",url:a.cardUrl}]:[{text:"Timer is OFF",url:""}]})},"card-badges":function(b,c){return getBackgroundBages(b,c)},"card-buttons":function(b,c){return[{text:"Agile by Origami",callback:function(a){return a.board("members").then(function(b){return a.popup({title:"Agile by Origami",url:"https://origami-powerup.github.io/TrelloPowerUp/settings.html",
args:{members:b},height:184})})}}]},"card-detail-badges":function(b,c){return getBadges(b)},"show-settings":function(b,c){return b.popup({title:"Agile by Origami",url:"https://origami-powerup.github.io/TrelloPowerUp/powerup.html",height:184})}});
